services:
  nginx:
    image: nginx:1.24.0 
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend_app:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - fastapi
    networks:
      - default

  fastapi:
    container_name: fastapi
    build: 
      context: ./fastapi_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"   # 개발용 (/docs)
    volumes:
      - ./fastapi_app:/app
    env_file:
      - .env
    restart: always
    environment:
      DATABASE_URL: "mysql+aiomysql://ngms:ms123@mysql_db:3306/PolitiSearch"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ELASTIC_USERNAME: "${ELASTIC_USERNAME}"
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD}"
    depends_on:
      - mysql_db
      - elasticsearch
    networks:
      - default

  frontend:
    build: ./frontend_app
    container_name: frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://localhost"
    depends_on:
      - fastapi
    networks:
      - default

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: ngms
      MYSQL_PASSWORD: ms123
      MYSQL_DATABASE: PolitiSearch
    ports:
      - "3307:3306"   # 로컬에서 접속 필요할 때만
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
    networks:
      - default

  elasticsearch:
    build:
      context: ./elasticsearch_app
      dockerfile: Dockerfile
    container_name: elasticsearch
    restart: always
    env_file: .env
    environment:
      - node.name=single-node
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - default

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    ports:
      - "5601:5601"
    restart: always
    env_file: .env
    environment:
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
      ELASTICSEARCH_USERNAME: ${KIBANA_USERNAME}
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
      XPACK_SECURITY_ENCRYPTIONKEY: ${XPACK_SECURITY_ENCRYPTIONKEY}
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: ${XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY}
      XPACK_REPORTING_ENCRYPTIONKEY: ${XPACK_REPORTING_ENCRYPTIONKEY}
    depends_on:
      - elasticsearch
    networks:
      - default

volumes:
  esdata:
  mysql_data:
