user nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events { 
    worker_connections 1024; 
    }

http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    # 1. FastAPI 백엔드 정의
    upstream api_backend {
        # Docker 서비스 이름과 포트
        server fastapi:8000;
    }

    # 2. Next.js 프론트엔드 정의
    upstream frontend_app {
        # Docker 서비스 이름과 포트
        server frontend:3000;
    }

    server {
        listen 80;
        server_name localhost;
        
        # API 요청 (/api/v1)은 FastAPI로 포워딩
        location /api/v1/ {
            proxy_pass http://api_backend/api/v1/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # FastAPI가 클라이언트 IP를 정확히 받도록 설정
        }

        # 프론트엔드 (Next.js)로 리버스 프록시
        location / {
            proxy_pass http://frontend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        

        # Nginx 기본 에러 처리
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root html;
        }
    }
}